## Math Using python

In [3]:
# imports
import numpy as np
import torch

In [2]:
# Vector and transpose
nv = np.array([[1, 2, 3, 4, 5, 6]])
print(nv)
nv_T = nv.T
print(nv_T)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [4]:
# Vector using pytorch
t_v = torch.tensor([[1, 2, 3, 4, 5, 6]])
print(t_v)

#Transpose a tensor
t_v_T = t_v.T
print(t_v_T)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [5]:
# matrix using tensor
t_m = torch.tensor([[0, 1,2, 3, 4], [5, 6, 7, 8, 9]])
print(t_m)

# matrix transpose
t_m_T = t_m.T
print(t_m_T)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])
