## Math Using python

In [13]:
# imports
import numpy as np
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# torch.set_default_device(device)

In [14]:
# Vector and transpose
nv = np.array([[1, 2, 3, 4, 5, 6]])
print(nv)
nv_T = nv.T
print(nv_T)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [15]:
# Vector using pytorch
t_v = torch.tensor([[1, 2, 3, 4, 5, 6]])
print(t_v)

#Transpose a tensor
t_v_T = t_v.T
print(t_v_T)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [16]:
# matrix using tensor
t_m = torch.tensor([[0, 1,2, 3, 4], [5, 6, 7, 8, 9]])
print(t_m)

# matrix transpose
t_m_T = t_m.T
print(t_m_T)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])


In [17]:
# Dot products numpy
n1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
n2 = np.array([[11,12,13,14,15], [16,17,18,19,20]])
n_dot = np.dot(n1, n2.T)
print(f'numpy dot product: {n_dot}', n_dot)

numpy dot product: [[205 280]
 [530 730]] [[205 280]
 [530 730]]


In [18]:
# Dot products pytorch
n_t1 = torch.tensor([[1.,2.,3.,4.,5.], [6.,7.,8.,9.,10.]]).to(device)
n_t2 = torch.tensor([[11.,12.,13.,14.,15.], [16.,17.,18.,19.,20.]]).to(device)

print(n_t1.shape, " : ", (n_t2.T.shape))
n_t_dot = n_t1.T @ n_t2
print(f'pytorch dot product: {n_t_dot }', n_t_dot )

torch.Size([2, 5])  :  torch.Size([5, 2])
pytorch dot product: tensor([[107., 114., 121., 128., 135.],
        [134., 143., 152., 161., 170.],
        [161., 172., 183., 194., 205.],
        [188., 201., 214., 227., 240.],
        [215., 230., 245., 260., 275.]], device='cuda:0') tensor([[107., 114., 121., 128., 135.],
        [134., 143., 152., 161., 170.],
        [161., 172., 183., 194., 205.],
        [188., 201., 214., 227., 240.],
        [215., 230., 245., 260., 275.]], device='cuda:0')
