# Numpy


In [3]:
import numpy as np

In [4]:
numbers = [1, 2, 3, 4, 5]
np.mean(numbers)

3.0

In [5]:
x = np.linspace(1, 7, 5)
type(x)

numpy.ndarray

In [6]:
numbers_np = np.array(numbers)
type(numbers_np)

numpy.ndarray

In [7]:
print(np.max(numbers_np))
print(np.min(numbers))
print(np.median(numbers))

5
1
3.0


In [8]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [9]:
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [31]:
# Dot product
def dot_product(vec1, vec2):

    if (
        type(vec1) == np.ndarray
        and type(vec2) == np.ndarray
        and vec1.shape == vec2.shape
    ):
        return np.dot(vec1, vec2.T)
    else:
        raise Exception("Shapes are not compaitible for dot product")

In [32]:
x = np.random.randn(10, 2)
y = np.random.randn(10, 2)
dot_product(x, y)

array([[-0.0198505 , -0.09283912, -0.19705537,  0.15768019, -0.07395896,
         0.03981695,  0.26802729, -0.21008946, -0.23467451,  0.14604788],
       [-0.26275137, -1.17721461, -2.43437367,  1.95680979, -0.95364476,
         0.40700485,  3.3176587 , -2.62341191, -2.96443391,  1.76778898],
       [-0.11800599,  0.19166162,  1.3327416 , -0.93878297, -0.07525132,
        -1.49126845, -1.71895157,  1.01754871,  0.64679764, -1.51250123],
       [-0.36054526,  0.19153189,  2.74484489, -1.87400581, -0.42303905,
        -3.64055056, -3.49657255,  1.90780614,  0.89407249, -3.3594982 ],
       [ 0.75788554,  1.28820288, -0.07548363, -0.32696508,  1.71790405,
         3.72335844, -0.18194774,  1.14348507,  2.76368534,  1.64827151],
       [-0.48441821, -1.22584537, -1.30717265,  1.2244753 , -1.295278  ,
        -1.44457714,  1.90911953, -1.95763903, -2.87165638,  0.23506507],
       [-0.2745921 , -0.28452278,  0.6409977 , -0.34128581, -0.53311991,
        -1.7724608 , -0.7457561 ,  0.14109861