# Numpy


In [3]:
import numpy as np

In [4]:
numbers = [1, 2, 3, 4, 5]
np.mean(numbers)

3.0

In [5]:
x = np.linspace(1, 7, 5)
type(x)

numpy.ndarray

In [6]:
numbers_np = np.array(numbers)
type(numbers_np)

numpy.ndarray

In [7]:
print(np.max(numbers_np))
print(np.min(numbers))
print(np.median(numbers))

5
1
3.0


In [8]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [9]:
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [33]:
# Dot product
def dot_product(vec1, vec2):

    if (
        type(vec1) == np.ndarray
        and isinstance(vec2, np.ndarray)
        and vec1.shape == vec2.shape
    ):
        return np.dot(vec1, vec2.T)
    else:
        raise Exception("Shapes are not compaitible for dot product")

In [34]:
x = np.random.randn(10, 2)
y = np.random.randn(10, 2)
dot_product(x, y)

array([[-1.32512582e+00, -1.86691078e+00, -2.25006032e+00,
         5.91566028e-01,  2.64119033e+00, -1.20085041e+00,
        -3.43921905e-01,  3.99998413e+00,  3.59160430e+00,
        -5.99580551e-01],
       [ 1.42771737e+00, -4.70718207e-01, -1.24004198e+00,
        -6.61491345e-01,  2.13301525e+00, -8.34988210e-01,
        -5.14737831e-01,  1.45015529e+00,  8.69851182e-01,
        -4.03079147e-01],
       [ 4.52991798e+00,  2.55675611e+00,  2.04476500e+00,
        -2.05943805e+00, -1.35624903e+00,  8.24396372e-01,
        -1.88616221e-01, -4.79746475e+00, -4.97380249e+00,
         4.32927978e-01],
       [ 1.79827185e+00,  1.46157150e+00,  1.47101668e+00,
        -8.13208049e-01, -1.43418004e+00,  7.10287996e-01,
         8.44071971e-02, -2.94080614e+00, -2.82723244e+00,
         3.60615919e-01],
       [-1.60950248e+00, -4.61519938e-01, -6.67658929e-02,
         7.36072479e-01, -4.14519237e-01,  9.03750211e-02,
         2.26410059e-01,  6.67520860e-01,  9.13877376e-01,
         3.