# Numpy


In [2]:
import numpy as np

In [3]:
numbers = [1, 2, 3, 4, 5]
np.mean(numbers)

3.0

In [4]:
x = np.linspace(1, 7, 5)
type(x)

numpy.ndarray

In [5]:
numbers_np = np.array(numbers)
type(numbers_np)

numpy.ndarray

In [6]:
print(np.max(numbers_np))
print(np.min(numbers))
print(np.median(numbers))

5
1
3.0


In [7]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [8]:
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [9]:
# Dot product
def dot_product(vec1, vec2):

    if (
        type(vec1) == np.ndarray
        and isinstance(vec2, np.ndarray)
        and vec1.shape == vec2.shape
    ):
        return np.dot(vec1, vec2.T)
    else:
        raise Exception("Shapes are not compaitible for dot product")

In [10]:
x = np.random.randn(10, 2)
y = np.random.randn(10, 2)
dot_product(x, y)

array([[ 0.67392442, -0.12592636, -0.56680395, -0.94359971, -0.52895343,
        -0.18103345, -0.26256179,  0.20594888, -0.72504933,  0.38277304],
       [ 2.71145626, -0.42598743,  0.6744346 ,  0.25320358,  3.11705815,
         1.30909618, -1.50246955,  0.28323452, -1.68759678, -3.81430732],
       [ 1.05383735, -0.16368867,  0.33085126,  0.19259705,  1.3334722 ,
         0.55618174, -0.59432629,  0.0973979 , -0.62730624, -1.60700342],
       [ 1.28440688, -0.23201487, -0.78779563, -1.39756483, -0.4889773 ,
        -0.14337182, -0.54455646,  0.33853279, -1.26015173,  0.19957883],
       [ 1.77724478, -0.30375806, -0.45695686, -1.06613403,  0.4472519 ,
         0.23816544, -0.84908589,  0.35157738, -1.48023631, -0.871073  ],
       [ 0.16409286, -0.00954362,  0.63560336,  0.8304741 ,  1.24444487,
         0.48934187, -0.18071824, -0.09263709,  0.1453644 , -1.3086037 ],
       [ 0.7461537 , -0.12146152,  0.03042091, -0.14298614,  0.58232105,
         0.25324911, -0.39003239,  0.10658196

## Seed in numpy


In [ ]:
# Not recomonded or old method
np.random.seed(100)
print(np.random.randn(5))  # Output does not change on re-execution
print(np.random.randn(5))  # Output does not change on re-execution

[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079]
[ 0.51421884  0.22117967 -1.07004333 -0.18949583  0.25500144]


In [ ]:
# More flexible and recomonded method of setting the random seed
s1 = np.random.RandomState(100)
s2 = np.random.RandomState(50000535)

print(s1.randn(5))  # Same sequence
print(s2.randn(5))  # Different from above but same every time
print(s2.randn(5))  # Same as two above
print(s2.randn(5))  # Same as two above
print(np.random.randn(5))  # Different every time

[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079]
[-0.0849423  -1.95431494  1.15960778 -1.37338818  0.13295008]
[-0.74621567  1.62900301 -1.14320064  0.89511699 -0.36598045]
[-0.80035017 -1.30925224 -0.15443611  0.65189402 -0.0653307 ]
[-1.04420988  0.61303888  0.73620521  1.02692144 -1.43219061]
