# Numpy


In [3]:
import numpy as np

In [4]:
numbers = [1, 2, 3, 4, 5]
np.mean(numbers)

3.0

In [5]:
x = np.linspace(1, 7, 5)
type(x)

numpy.ndarray

In [6]:
numbers_np = np.array(numbers)
type(numbers_np)

numpy.ndarray

In [7]:
print(np.max(numbers_np))
print(np.min(numbers))
print(np.median(numbers))

5
1
3.0


In [8]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [9]:
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [24]:
# Dot product
def dot_product(vec1, vec2):
    if vec1.shape == vec2.shape:
        return np.dot(vec1, vec2.T)
    else:
        raise Exception("Shapes are not compaitible for dot product")

In [25]:
x = np.random.randn(10, 2)
y = np.random.randn(10, 2)
dot_product(x, y)

array([[-2.66851408e-01, -1.89856969e-01, -3.72216033e-01,
        -8.63906394e-02, -1.12040596e-01,  1.64309228e-01,
        -3.33202148e-01,  6.61139378e-01,  7.44264432e-02,
         4.05462894e-01],
       [ 1.29427345e-01,  9.95909746e-02,  1.61146072e-01,
         2.11263590e-02,  1.54579749e-02, -7.40414342e-02,
         1.28597654e-01, -2.41769893e-01, -4.97348731e-02,
        -1.35277158e-01],
       [-6.05542615e-01, -4.37325351e-01, -8.27854579e-01,
        -1.78052820e-01, -2.20579805e-01,  3.67959917e-01,
        -7.27526786e-01,  1.43196233e+00,  1.80695752e-01,
         8.66941557e-01],
       [ 8.16428763e-01,  5.85668194e-01,  1.12638842e+00,
         2.51019870e-01,  3.17909679e-01, -4.99086559e-01,
         9.98308122e-01, -1.97227305e+00, -2.36431497e-01,
        -1.20123944e+00],
       [-1.00644213e-01, -7.58039371e-03, -3.05706273e-01,
        -2.09757704e-01, -3.73874195e-01,  1.10166592e-01,
        -4.07201353e-01,  9.22194224e-01, -8.82310049e-02,
         6.