In [3]:
# Imports
import torch
import torch.nn as nn
import torch.nn.functional as F

# Pytorch device specific configuration
# Pytorch Gpu Configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.set_default_device(device)

In [ ]:
# Dropout using pytorch nn module
prob = 0.4

dropout = nn.Dropout(p=prob)
x = torch.ones(15)

# Dropout
y = dropout(x)
print(x)
print(y * (1 - prob))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')
tensor([0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1.],
       device='cuda:0')
tensor(0.8889, device='cuda:0')


In [7]:
# Dropout Evaluation mode
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')
tensor(1., device='cuda:0')


In [17]:
# Eval need to be toggeled to go in to training mode
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

tensor([0.0000, 1.6667, 1.6667, 1.6667, 0.0000, 1.6667, 0.0000, 1.6667, 1.6667,
        1.6667, 0.0000, 1.6667, 0.0000, 1.6667, 1.6667], device='cuda:0')
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')


In [14]:
# Dropout using pytorch functional module
y = F.dropout(x, p=prob)
print(y)
print(torch.mean(y))

tensor([1.6667, 0.0000, 1.6667, 0.0000, 1.6667, 1.6667, 0.0000, 1.6667, 0.0000,
        0.0000, 1.6667, 1.6667, 0.0000, 0.0000, 1.6667], device='cuda:0')
tensor(0.8889, device='cuda:0')


In [18]:
# Function dropout eval mode
y = F.dropout(x, p=prob, training=False)
print(y)
print(torch.mean(y))

# Functional dropout train mode toggle after eval mode
y = F.dropout(x, p=prob, training=True)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')
tensor(1., device='cuda:0')
tensor([0.0000, 0.0000, 1.6667, 0.0000, 0.0000, 0.0000, 0.0000, 1.6667, 1.6667,
        1.6667, 0.0000, 0.0000, 1.6667, 1.6667, 1.6667], device='cuda:0')
tensor(0.7778, device='cuda:0')
